export {default as Home } from './Home'
export {default as Compare} from './Compare'
export {default as LoginRedirect } from './LoginRedirect'
export {default as Login } from './Login'
export {default as SignUp} from './SignUp'
export {default as ForgotPassword} from './ForgotPassword'